#!/usr/bin/env bash

# shellcheck disable=SC2154
command="$1"

set -ueo pipefail

CMDS="init-simple init-alt"

TRACE=${TRACE:-""}
[[ "$TRACE" ]] && set -x

abort() {
	local msg="$1"
	echo "$msg"
	exit -1
}

# set to echo to enable debugging
debug=${DEBUG:-""}
case "$debug" in
"" | echo) ;;

*)
	abort "Invalid value: $debug for DEBUG. Only empty string and echo are allowed."
	;;
esac

run() {
	$debug "$@"
}

init_shared() {
	run mkdir -p library module_utils filter_plugins roles
	run touch {library,module_utils,filter_plugins,roles}/.keep
	run touch site.yml
}

init_alt() {
	init_shared
	run mkdir -p inventories/development/{group_vars,host_vars}
	run touch inventories/development/{group_vars,host_vars}/.keep
}

init_simple() {
	init_shared
	run mkdir -p group_vars host_vars
	run touch {group_vars,host_vars}/.keep
	run touch development.ini
}

main() {
	local cmd=$1
	case "$cmd" in
	init-simple)
		init_simple
		;;
	init-alt)
		init_alt
		;;
	*)
		abort "Invalid command: '$cmd'. Available commands: $CMDS"
		;;
	esac
}

main "$command"
